kiosk_mode:
  mobile_settings:
    hide_header: true
    custom_width: 1025
views:
  - title: Home
    theme: Nordic Blue Dark
    hide_toolbar: true
    hide_sidebar: true
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: https://light.cherrypink.toys/home
            aspect_ratio: 40%
            visibility:
              - condition: state
                entity: switch.optika
                state: 'on'
          - type: iframe
            url: https://light.cherrypink.toys/home?yellow=1
            aspect_ratio: 40%
            visibility:
              - condition: state
                entity: switch.optika
                state_not: 'on'
          - type: history-graph
            entities:
              - entity: switch.optika
            logarithmic_scale: false
      - type: vertical-stack
        cards:
          - clock_style: analog
            clock_size: large
            show_seconds: true
            no_background: false
            border: true
            ticks: minute
            face_style: numbers_upright
            type: clock
            seconds_motion: continuous
          - type: entities
            entities:
              - entity: binary_sensor.m_kiiv_air
                secondary_info: last-changed
            title: ПОВІТРЯНА ТРИВОГА
            state_color: true
            show_header_toggle: false
          - type: iframe
            url: https://alerts.in.ua/?kiosk&showThreats&showWarnings
            aspect_ration: 50
          - type: history-graph
            entities:
              - entity: binary_sensor.m_kiiv_air
      - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              - show_current: true
                show_forecast: true
                type: weather-forecast
                entity: weather.forecast_home
                forecast_type: hourly
                name: ' '
      - type: vertical-stack
        cards:
          - square: false
            type: grid
            columns: 2
            cards:
              - show_name: true
                show_icon: true
                type: button
                name: ЕЛЕКТРО
                entity: switch.detektor_dtek_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: ДРОВА
                entity: switch.tverdopalivnii_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
          - type: grid
            columns: 3
            square: false
            cards:
              - show_name: true
                show_icon: true
                type: button
                name: ПЕРШИЙ
                entity: switch.boiler_drugii_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: ДРУГИЙ
                entity: switch.drugii_klapan_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: ПІДЛОГА
                entity: switch.teplii_pol_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
          - type: vertical-stack
            cards:
              - square: false
                type: grid
                columns: 4
                cards:
                  - show_name: true
                    show_icon: true
                    type: button
                    name: БОЙЛЕР1
                    entity: switch.boiler
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: БОЙЛЕР2
                    entity: switch.boiler_drugii
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: ГАРАЖ1
                    entity: switch.poliv_3
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: ГАРАЖ2
                    entity: switch.poliv_1
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
      - type: vertical-stack
        cards:
          - square: false
            type: grid
            columns: 2
            cards:
              - type: entities
                entities:
                  - entity: sensor.kukhnia_th2_temperature
                    secondary_info: none
                    name: ' '
                  - entity: sensor.kukhnia_th2_humidity
                    secondary_info: none
                    name: ' '
                show_header_toggle: false
                state_color: false
                title: кухня
              - type: entities
                entities:
                  - entity: sensor.gostova_th2_temperature
                    secondary_info: none
                    name: ' '
                  - entity: sensor.gostova_th2_humidity
                    secondary_info: none
                    name: ' '
                show_header_toggle: false
                state_color: false
                title: гостьова
          - square: false
            type: grid
            columns: 2
            cards:
              - type: entities
                entities:
                  - entity: sensor.mama_th2_temperature
                    secondary_info: none
                    name: ' '
                  - entity: sensor.mama_th2_humidity
                    secondary_info: none
                    name: ' '
                show_header_toggle: false
                state_color: false
                title: мама
              - type: entities
                entities:
                  - entity: sensor.drugii_th2_temperature
                    secondary_info: none
                    name: ' '
                  - entity: sensor.drugii_th2_humidity
                    secondary_info: none
                    name: ' '
                show_header_toggle: false
                state_color: false
                title: другий
          - square: false
            type: grid
            columns: 2
            cards:
              - type: entities
                entities:
                  - entity: sensor.drugii_th2_temperature
                    secondary_info: none
                    name: ' '
                  - entity: sensor.drugii_th2_humidity
                    secondary_info: none
                    name: ' '
                show_header_toggle: false
                state_color: false
                title: другий
              - type: entities
                entities:
                  - entity: sensor.drugii_th2_temperature
                    secondary_info: none
                    name: ' '
                  - entity: sensor.drugii_th2_humidity
                    secondary_info: none
                    name: ' '
                show_header_toggle: false
                state_color: false
                title: другий
    badges: []
  - title: testpanel
    path: testpanel
    badges:
      - type: entity
        entity: switch.boiler
      - type: entity
        entity: switch.boiler_drugii
    type: masonry
    theme: Nordic Blue Dark
    cards:
      - square: false
        type: grid
        columns: 3
        cards:
          - type: entities
            entities:
              - entity: sensor.kukhnia_th2_temperature
                secondary_info: none
                name: ' '
              - entity: sensor.kukhnia_th2_humidity
                secondary_info: none
                name: ' '
            show_header_toggle: false
            state_color: false
            title: кухня
          - type: entities
            entities:
              - entity: sensor.gostova_th2_temperature
                secondary_info: none
                name: ' '
              - entity: sensor.gostova_th2_humidity
                secondary_info: none
                name: ' '
            show_header_toggle: false
            state_color: false
            title: гостьова
          - type: entities
            entities:
              - entity: sensor.mama_th2_temperature
                secondary_info: none
                name: ' '
              - entity: sensor.mama_th2_humidity
                secondary_info: none
                name: ' '
            show_header_toggle: false
            state_color: false
            title: мама
      - square: false
        type: grid
        columns: 3
        cards:
          - type: entities
            entities:
              - entity: sensor.drugii_th2_temperature
                secondary_info: none
                name: ' '
              - entity: sensor.drugii_th2_humidity
                secondary_info: none
                name: ' '
            show_header_toggle: false
            state_color: false
            title: другий
          - type: entities
            entities:
              - entity: sensor.drugii_th2_temperature
                secondary_info: none
                name: ' '
              - entity: sensor.drugii_th2_humidity
                secondary_info: none
                name: ' '
            show_header_toggle: false
            state_color: false
            title: другий
          - type: entities
            entities:
              - entity: sensor.drugii_th2_temperature
                secondary_info: none
                name: ' '
              - entity: sensor.drugii_th2_humidity
                secondary_info: none
                name: ' '
            show_header_toggle: false
            state_color: false
            title: другий
