kiosk_mode:
  mobile_settings:
    hide_header: true
    custom_width: 1025
views:
  - title: Home
    theme: Nordic Blue Dark
    hide_toolbar: true
    hide_sidebar: true
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: https://light.cherrypink.toys/home
            aspect_ratio: 40%
            visibility:
              - condition: state
                entity: switch.optika
                state: 'on'
          - type: iframe
            url: https://light.cherrypink.toys/home?yellow=1
            aspect_ratio: 40%
            visibility:
              - condition: state
                entity: switch.optika
                state_not: 'on'
            logarithmic_scale: false
          - type: entities
            entities:
              - entity: automation.nova_avtomatizatsiia_3
                icon: mdi:stove
              - entity: automation.vikl_kotel
                icon: mdi:stove
              - entity: automation.vkl_gostova
                icon: mdi:pipe-valve
              - entity: automation.vikl_gostova
                icon: mdi:pipe-valve
              - entity: automation.vkl_kukhnia
                icon: mdi:pipe-valve
              - entity: automation.nova_avtomatizatsiia_2
                icon: mdi:pipe-valve
              - entity: automation.vkl_drugii
                icon: mdi:pipe-valve
              - entity: automation.vikl_drugii
                icon: mdi:pipe-valve
              - entity: automation.vkl_pershii
                icon: mdi:pipe-valve
              - entity: automation.vikl_pershii
                icon: mdi:pipe-valve
              - entity: automation.vkliuchit_teplii_pol_bo_zharko_na_drugomu
                icon: mdi:pipe
              - entity: automation.zakhist_vikl_el_kotel
                icon: mdi:close-octagon
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: automation.vkliuchit_boiler_pershii
                icon: mdi:water-boiler
              - entity: automation.vimknuti_boiler_pershii
                icon: mdi:water-boiler
              - entity: automation.vkliuchit_boiler_drugii
                icon: mdi:water-boiler
              - entity: automation.vikliuchit_boiler_drugii
                icon: mdi:water-boiler
              - entity: automation.vimknuti_zariad_avto
                icon: mdi:car
              - entity: automation.vkliuchit_zariad_avto
                icon: mdi:car
              - entity: automation.vimknuti_zariad_avto_bo_nema_dtek
                name: 'Захист: Виключить заряд авто'
                icon: mdi:close-octagon
              - entity: automation.nova_avtomatizatsiia
                icon: mdi:weather-pouring
      - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              - type: iframe
                url: https://alerts.in.ua/?kiosk&showThreats&showWarnings
                aspect_ration: 50
              - type: history-graph
                entities:
                  - entity: binary_sensor.m_kiiv_air
      - type: vertical-stack
        cards:
          - square: false
            type: grid
            columns: 2
            cards:
              - show_name: true
                show_icon: true
                type: button
                name: ЕЛЕКТРО
                entity: switch.detektor_dtek_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: Дрова
                entity: switch.tverdopalivnii_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
          - type: grid
            columns: 3
            square: false
            cards:
              - show_name: true
                show_icon: true
                type: button
                name: Перший
                entity: switch.boiler_drugii_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: Гостьова
                entity: switch.boiler_klapan_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: Кухня
                entity: switch.generator_tumanu_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: Підлога
                entity: switch.teplii_pol_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: Другий
                entity: switch.drugii_klapan_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
              - show_name: true
                show_icon: true
                type: button
                name: Гольф
                entity: switch.garazhavto_socket_1
                icon: mdi:power
                show_state: false
                tap_action:
                  action: toggle
          - type: vertical-stack
            cards:
              - square: false
                type: grid
                columns: 3
                cards:
                  - show_name: true
                    show_icon: true
                    type: button
                    name: Бойлер 1
                    entity: switch.boiler
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                    confirmation:
                      text: |
                        {% if is_state('switch.boiler_drugii', 'off') %}
                          Інший перемикач вимкнено. Увімкнути бойлер попри це?
                        {% else %}
                          Ви впевнені, що хочете перемкнути бойлер?
                        {% endif %}
                  - show_name: true
                    show_icon: true
                    type: button
                    name: Бойлер 2
                    entity: switch.boiler_drugii
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: Оптика
                    entity: switch.faust
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: Гараж 1
                    entity: switch.garazh_1_nova
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: Гараж 2
                    entity: switch.poliv_1
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
                  - show_name: true
                    show_icon: true
                    type: button
                    name: ДТЕК
                    entity: switch.podacha_dtek
                    icon: mdi:power
                    show_state: false
                    tap_action:
                      action: toggle
      - type: vertical-stack
        cards:
          - square: false
            type: grid
            columns: 2
            cards:
              - type: entity
                entity: sensor.kukhnia_th2_temperature
                name: Кухня
                state_color: false
              - type: entity
                entity: sensor.gostova_th2_temperature
                name: Гостьова
                state_color: false
          - square: false
            type: grid
            columns: 2
            cards:
              - type: entity
                entity: sensor.mama_th2_temperature
                name: Мама
                state_color: false
              - type: entity
                entity: sensor.drugii_th2_temperature
                name: Другий
                state_color: false
          - square: false
            type: grid
            columns: 2
            cards:
              - type: entity
                entity: sensor.temperatura_i_vologist_drugii_poverkh_temperature
                name: Дитяча
                state_color: false
    badges: []
  - title: testpanel
    path: testpanel
    badges:
      - type: entity
        entity: switch.boiler
      - type: entity
        entity: switch.boiler_drugii
    type: masonry
    theme: Nordic Blue Dark
    cards:
      - type: entities
        entities:
          - entity: automation.nova_avtomatizatsiia_3
            icon: mdi:stove
          - entity: automation.vikl_kotel
            icon: mdi:stove
          - entity: automation.vkl_gostova
            icon: mdi:pipe-valve
          - entity: automation.vikl_gostova
            icon: mdi:pipe-valve
          - entity: automation.vkl_kukhnia
            icon: mdi:pipe-valve
          - entity: automation.nova_avtomatizatsiia_2
            icon: mdi:pipe-valve
          - entity: automation.vkl_drugii
            icon: mdi:pipe-valve
          - entity: automation.vikl_drugii
            icon: mdi:pipe-valve
          - entity: automation.vkl_pershii
            icon: mdi:pipe-valve
          - entity: automation.vikl_pershii
            icon: mdi:pipe-valve
          - entity: automation.vkliuchit_teplii_pol_bo_zharko_na_drugomu
            icon: mdi:pipe
          - entity: automation.zakhist_vikl_el_kotel
            icon: mdi:close-octagon
        title: Автоматизації Опалення
        show_header_toggle: false
      - type: entities
        entities:
          - entity: automation.vkliuchit_boiler_pershii
            icon: mdi:water-boiler
          - entity: automation.vimknuti_boiler_pershii
            icon: mdi:water-boiler
          - entity: automation.vkliuchit_boiler_drugii
            icon: mdi:water-boiler
          - entity: automation.vikliuchit_boiler_drugii
            icon: mdi:water-boiler
          - entity: automation.vimknuti_zariad_avto
            icon: mdi:car
          - entity: automation.vkliuchit_zariad_avto
            icon: mdi:car
          - entity: automation.vimknuti_zariad_avto_bo_nema_dtek
            name: 'Захист: Виключить заряд авто'
            icon: mdi:close-octagon
          - entity: automation.nova_avtomatizatsiia
            icon: mdi:weather-pouring
        title: Інші Автоматизації
      - type: entities
        entities:
          - entity: sensor.yasno_group_4_2_electricity
            name: Electricity
          - entity: sensor.yasno_group_4_2_next_connectivity
            name: Next Connectivity
          - entity: sensor.yasno_group_4_2_next_outage
            name: Next Outage
          - entity: sensor.yasno_group_4_2_next_possible_outage
            name: Next Possible Outage
          - entity: calendar.yasno_group_4_2_outages_calendar
            name: Outages Calendar
        title: Yasno Group 4.2
      - type: entities
        entities:
          - entity: switch.optika_auto_off_enabled
            name: Auto-off enabled
          - entity: switch.optika_auto_update_enabled
            name: Auto-update enabled
          - entity: switch.optika_led
            name: LED
          - entity: number.optika_turn_off_in
            name: Turn off in
        title: детектор дтек
      - type: entities
        entities:
          - entity: sensor.yasno_kiiv_dtek_4_2_electricity
            name: Electricity
          - entity: sensor.yasno_kiiv_dtek_4_2_next_connectivity
            name: Next Connectivity
          - entity: sensor.yasno_kiiv_dtek_4_2_next_planned_outage
            name: Next Planned Outage
          - entity: sensor.yasno_kiiv_dtek_4_2_next_probable_outage
            name: Next Probable Outage
          - entity: calendar.yasno_kiiv_dtek_4_2_planned_outages
            name: Planned Outages
          - entity: calendar.yasno_kiiv_dtek_4_2_probable_outages
            name: Probable Outages
        title: Yasno Київ ДТЕК 4.2
